Repository KnpLabs/KnpTimeBundle, pull requests merged in 2020-12, with the labels that each got.

#143 Update README.md
  README.md
Labels: Related Tests Pass, Status: Reviewed

#144 Update composer.json
  composer.json
Labels: Related Tests Pass, Status: Reviewed

#149 Update/doc
  README.md
Labels: Related Tests Pass

#147 Add compatibility for PHP 8.0
  .travis.yml
  README.md
  Tests/DateTimeFormatterTest.php
  composer.json
  phpunit.xml.dist
Labels: Status: Reviewed
